### ISSUE TITLE
Схема нормальная где? Не разводка платы.

### ISSUE THREAD

**Issue by eXPert-nnm4evr** [ValeraKirpich/Pandora-battery-for-PSP-on-arduino#1]
Почему нет нормальной схемы? Вот я например буду использовать компоненты в SMD исполнении (включая МК (atmega328p) и К561ЛМ7 (CD4011, а точнее HEF4011)), хотелось бы что-бы была нормальная принципиальная схема.

**Comment by ValeraKirpich** [comment]
Привет. Я схему и плату хотел переделать под смд, и нарисовать
принципиальную схему, но времени на это пока не могу найти

пн, 6 дек. 2021 г. в 19:57, eXPert-nnm4evr ***@***.***>:

**Comment by eXPert-nnm4evr** [comment]
Вот быстрый (очень быстрый) набросок схемы в программе DipTrace. Позже могу залить куда-нибудь исходник и необходимые библиотеки.
![Shematic_1](https://user-images.githubusercontent.com/85419258/146256976-4ebadead-04a2-42d3-8b50-fd502457d467.png)

**Comment by ily25198** [comment]
Has starred ~Is there a final schematic？

**Comment by ily25198** [comment]
> Вот быстрый (очень быстрый) набросок схемы в программе DipTrace. Позже могу залить куда-нибудь исходник и необходимые библиотеки. ![Shematic_1](https://user-images.githubusercontent.com/85419258/146256976-4ebadead-04a2-42d3-8b50-fd502457d467.png)

It seems that there is a 22k less resistance than the author's circuit diagram

**Comment by ValeraKirpich** [comment]
Новые схемы добавлены в проект
