### ISSUE TITLE
Подойдет ли CD4011 без переделки схемы?

### ISSUE THREAD

**Issue by bumbec** [ValeraKirpich/Pandora-battery-for-PSP-on-arduino#3]
Подойдет ли CD4011 без переделки схемы?

**Comment by ily25198** [comment]
The need to make some design change , only need to change the two and not gate circuit leads is Ok~

**Comment by bumbec** [comment]
Отвечу сам себе. Да подходит CD4011B без переделки схемы.

**Comment by ily25198** [comment]
Did you manage to build the battery

**Comment by ily25198** [comment]
<img width="444" alt="Snipaste_CD4011" src="https://github.com/ValeraKirpich/Pandora-battery-for-PSP-on-arduino/assets/69613543/7c0604ac-4cca-4246-9841-638f2b75d597">,I changed the schematic to follow the difference between 57 and CD4011 and not gates

**Comment by bumbec** [comment]
![1](https://github.com/ValeraKirpich/Pandora-battery-for-PSP-on-arduino/assets/124337969/0769e162-826e-4c61-be9b-101ae2998ff7)

**Comment by ily25198** [comment]
> ![1](https://user-images.githubusercontent.com/124337969/266937661-0769e162-826e-4c61-be9b-101ae2998ff7.PNG)

Great, you also used a smaller package of circuits, this is verified to work?

**Comment by ily25198** [comment]
![Uploading 微信图片_20230911014436.jpg…]()

**Comment by bumbec** [comment]
[baryon sweeper.zip](https://github.com/ValeraKirpich/Pandora-battery-for-PSP-on-arduino/files/12603182/baryon.sweeper.zip)

**Comment by ily25198** [comment]
Thank U~I will make PCB sample ~

**Comment by jas0npc** [comment]
> Thank U~I will make PCB sample ~

Could you please post your Gerber file so I can use it with jlcpcb please

**Comment by ily25198** [comment]
I haven't had time to do it recently. I'll send it back when it's done
